'''
Elements container.
Contains information about GUI elements, like variables names, labels, and other elements.
Logic how to setup is in _populate_window method of every window class file.
'''

# Setting radiobuttons
radiobuttons_name_prefix = 'checkBox'
radiobuttons_name_postfix = [('ColorKeyImages'),
                             ('Animation', ''),
                             ('ViewGrowthTypes', ''),
                             ('ECHO', ''),
                             ('COEFFile', ''),
                             ('AVGFile', ''),
                             ('STDDEVFile', ''),
                             ('MEMORYMap', ''),
                             ('LOGGING', ''),
                             ('LogLandclassSummary', ''),
                             ('LogSlopeWeight', ''),
                             ('LogReads', ''),
                             ('LogWrites', ''),
                             ('LogColortables', ''),
                             ('LogTransitionMatrix', ''),
                             ('LogUrbanizationAttempts', ''),
                             ('LogInitialCoefficients', ''),
                             ('LogBaseStatistics', ''),
                             ('LogDebug', ''),
                             ('LogProcessingStatus', ''),
                             ('LogTimings', ''),
                             ('WorkingGrids', ''),
                             ('RandomSeed', ''),
                             ('MontecarloIterations', ''),
                             ('AuxDiffusionMult', ''),
                             ('AuxDiffustionCoeff', ''),
                             ('AuxBreedCoeff', ''),
                             ('WriteRatioFile', ''),
                             ('WriteSlopeFile', ''),
                             ('WriteXYPointsFile', ''),
                             ('ViewDeltatronAging', '')]

# Setting buttons
buttons_name_prefix = 'button'
# Variable name, label on button, bound layout
buttons_name_postfix_and_text = [('UrbanDataImage', 'Wybierz z dysku'),
                                 ('RoadDataImage', 'Wybierz z dysku'),
                                 ('LanduseDataImage', 'Wybierz z dysku'),
                                 ('ExcludedDataImage', 'Wybierz z dysku'),
                                 ('SlopeDataImage', 'Wybierz z dysku'),
                                 ('BackgroundDataImage', 'Wybierz z dysku'),
                                 ('OutputFilesColorSettings',
                                  'Output File Color Settings',
                                  'labelColorsSettingsButtons',
                                  ''),
                                 ('ProbabilityColorSettings',
                                  'Probability Colortable Color Settings',
                                  'labelColorsSettingsButtons',
                                  ''),
                                 ('DeltatronAgingColortable',
                                  'Color settings for deltatron aging',
                                  'labelColorsSettingsButtons',
                                  '')]

# Setting labels
# Attach element to label
labels_name_prefix = 'label'
labels_name_postfix_and_text = [('SleuthModel', 'SLEUTH Model: ', 'topRow'),
                                ('Simulation', 'SIMULATION: ', 'topRow'),
                                ('ModelDate', 'Model date: ', 'topRow'),
                                ('SimulationDate', 'Simulation date: ', 'topRow'),
                                ('InputOutputDirectoryMain', 'INput / OUTput DIRECTORY', 'leftColumn'),
                                ('DataDirectory', 'DATA DIRECTORY: ', 'leftColumn'),
                                ('OutputDirectory', 'OUTPUT DIRECTORY: ', 'leftColumn'),
                                ('PredictionRange', 'PREDICTION RANGE', 'middleColumn'),
                                ('RunningStatusVariables', 'RUNNING status & variables', 'rightColumn'),
                                ('StartDate', 'START Date: ', 'middleColumn'),
                                ('StopDate', 'STOP Date: ', 'middleColumn'),
                                ('InputImages', 'INPUT IMAGES', 'leftColumnt'),
                                ('OutputImages', 'OUTPUT IMAGES', 'leftColumnt'),
                                ('Coefficients', 'COEFFICIENTS', 'middleColumn'),
                                ('SelfModificationParameters', 'SELF-MODIFICATION PARAMETERS', 'middleColumn'),
                                ('LogFilePreferences', 'LOG FILE preferences', 'rightColumn'),
                                ('DeltatronAgingSection', 'DELTATRON AGING SECTION', 'rightColumn'),
                                ('WriteColorKeyImages', 'WRITE COLOR KEY IMAGES', 'leftColumn'),
                                ('Animation', 'ANIMATION', 'leftColumn'),
                                ('ViewGrowthTypes', 'VIEW GROWTH TYPES (YES/NO)', 'leftColumn'),
                                ('GrowthTypePrintWindow', 'GROWTH TYPE PRINT WINDOW', 'leftColumn'),
                                ('Echo', 'ECHO', 'rightColumnt'),
                                ('COEFFile', 'COEF File', 'rightColumnt'),
                                ('AVGFile', 'AVG File', 'rightColumnt'),
                                ('STDDEVFile', 'STD DEV file', 'rightColumnt'),
                                ('MEMORYmap', 'MEMORY map', 'rightColumnt'),
                                ('LOGGING', 'LOGGING', 'rightColumnt'),
                                ('UrbanImage', 'Urban image: ', 'leftColumn'),
                                ('RoadDataImage', 'Road data image: ', 'leftColumn'),
                                ('LanduseDataImage', 'Land use data image: ', 'leftColumn'),
                                ('ExcludedDataImage', 'Excluded data image: ', 'leftColumn'),
                                ('SlopeDataImage', 'Slope data image: ', 'leftColumn'),
                                ('BackgroundDataImage', 'Background data image: ', 'leftColumn'),
                                ('CalibDiffStart', 'CALIBRATION_DIFFUSION_START', 'middleColumn'),
                                ('CalibDiffStep', 'CALIBRATION_DIFFUSTION_STEP', 'middleColumn'),
                                ('CalibDiffStop', 'CALIBRATION_DIFFUSTION_STOP', 'middleColumn'),
                                ('CalibBreedStart', 'CALIBRATION_BREED_START', 'middleColumn'),
                                ('CalibBreedStep', 'CALIBRATION_BREED_STEP', 'middleColumn'),
                                ('CalibBreedStop', 'CALIBRATION_BREED_STOP', 'middleColumn'),
                                ('CalibSpreadStart', 'CALIBRATION_SPREAD_START', 'middleColumn'),
                                ('CalibSpreadStep', 'CALIBRATION_SPREAD_STEP', 'middleColumn'),
                                ('CalibSpreadStop', 'CALIBRATION_SPREAD_STOP', 'middleColumn'),
                                ('CalibSlopeStart', 'CALIBRATION_SLOPE_START', 'middleColumn'),
                                ('CalibSlopeStep', 'CALIBRATION_SLOPE_STEP', 'middleColumn'),
                                ('CalibSlopeStop', 'CALIBRATION_SLOPE_STOP', 'middleColumn'),
                                ('CalibRoadStart', 'CALIBRATION_ROAD_START', 'middleColumn'),
                                ('CalibRoadStep', 'CALIBRATION_ROAD_STEP', 'middleColumn'),
                                ('CalibRoadStop', 'CALIBRATION_ROAD_STOP', 'middleColumn'),
                                ('PredDiffBestFit', 'PREDICTION_DIFFUSION_BEST_FIT', 'middleColumn'),
                                ('PredBreedBestFit', 'PREDICTION_BREED_BEST_FIT', 'middleColumn'),
                                ('PredSpreadBestFit', 'PREDICTION_SPREAD_BEST_FIT', 'middleColumn'),
                                ('PredSlopeBestFit', 'PREDICTION_SLOPE_BEST_FIT', 'middleColumn'),
                                ('PredRoadBestFit', 'PREDICTION_ROAD_BEST_FIT', 'middleColumn'),
                                ('RoadGravSensitivity', 'ROAD_GRAV_SENSITIVITY', 'middleColumn'),
                                ('SlopeSensitivity', 'SLOPE_SENSITIVITY', 'middleColumn'),
                                ('CriticalLow', 'CRITICAL_LOW', 'middleColumn'),
                                ('CriticalHigh', 'CRITICAL_HIGH', 'middleColumn'),
                                ('CriticalSlope', 'CRITICAL_SLOPE', 'middleColumn'),
                                ('Boom', 'BOOM', 'middleColumn'),
                                ('Bust', 'BUST', 'middleColumn'),
                                ('LogLandclassSummary', 'LOG_LANDCLASS_SUMMARY', 'rightColumn'),
                                ('LogSlopeWeight', 'LOG_SLOPE_WEIGHT', 'rightColumn'),
                                ('LogReads', 'LOG_READS', 'rightColumn'),
                                ('LogWrites', 'LOG_WRITES', 'rightColumn'),
                                ('LogColortables', 'LOG_COLORTABLES', 'rightColumn'),
                                ('LogTransitionMatrix', 'LOG_TRANSITION_MATRIX', 'rightColumn'),
                                ('LogUrbanizationAttempts', 'LOG_URBANIZATION_ATTEMPTS', 'rightColumn'),
                                ('LogInitialCoefficients', 'LOG_INITIAL_COEFFICIENTS', 'rightColumn'),
                                ('LogBaseStatistics', 'LOG_BASE_STATISTICS', 'rightColumn'),
                                ('LogDebug', 'LOG_DEBUG', 'rightColumn'),
                                ('LogProcessingStatus', 'LOG_PROCESSING_STATUS', 'rightColumn'),
                                ('LogTimings', 'LOG_TIMINGS', 'rightColumn'),
                                ('WorkingGrids', 'WORKING GRIDS', 'rightColumn'),
                                ('RandomSeed', 'RANDOM SEED', 'rightColumn'),
                                ('MontecarloIterations', 'MONTECARLO ITERATIONS', 'rightColumn'),
                                ('AuxDiffusionMult', 'AUX_DIFFUSION_MULT', 'rightColumn'),
                                ('AuxDiffusionCoeff', 'AUX_DIFFUSION_COEFF', 'rightColumn'),
                                ('AuxBreedCoeff', 'AUX_BREED_COEFF', 'rightColumn'),
                                ('WriteRatioFile', 'WRITE_RATIO_FILE', 'rightColumn'),
                                ('WriteSlopeFile', 'WRITE_SLOPE_FILE', 'rightColumn'),
                                ('WriteXYPointsFile', 'WRITE_XYPOINTS_FILE', 'rightColumn'),
                                ('ViewDeltatronAging', 'VIEW_DELTATRON_AGING', 'rightColumn'),
                                ('DeltatronPrintWindow', 'DELTATRON_PRINT_WINDOW', 'rightColumn'),
                                ('ColorSettingsButtons', 'Color settings buttons: ', 'bottowmRow')]

labels_qt_align_center = ['labelInputOutputDirectoryMain',
                          'labelPredictionRange',
                          'labelRunningStatusVariables',
                          'labelInputImages',
                          'labelCoefficients',
                          'labelLogFilePreferences',
                          'labelOutputImages',
                          'labelSelfModificationParameters',
                          'labelDeltatronAgingSection']

# Setting lineEdits
line_edits_name_prefix = 'lineEdit'
# Variable name, label of lineEdit, width, length, bound layout
line_edits_name_postfix_and_text_width_maxlength = [('SleuthModelName', 'Nazwa modelu', None, None),
                                                    ('Simulation', 'Nazwa scenariusza', None, None),
                                                    ('ModelDate', '1.1.1970', 70, 10),
                                                    ('SimulationDate', '1.1.1970', 70, 10),
                                                    ('StartRun', 'Start run', None, None),
                                                    ('EndRun', 'End run', None, None),
                                                    ('StartMc', 'Start mc', None, None),
                                                    ('EndMc', 'End mc', None, None),
                                                    ('StartYear', 'Start year', None, None),
                                                    ('EndYear', 'End year', None, None),
                                                    ('StartRunDeltatron', 'Start run', None, None),
                                                    ('EndRunDeltatron', 'End run', None, None),
                                                    ('StartMcDeltatron', 'Start mc', None, None),
                                                    ('EndMcDeltatron', 'End mc', None, None),
                                                    ('StartYearDeltatron', 'Start year', None, None),
                                                    ('EndYearDeltatron', 'End year', None, None),
                                                    ('UrbanImage', '', None, None),
                                                    ('RoadDataImage', '', None, None),
                                                    ('LanduseDataImage', '', None, None),
                                                    ('ExcludedDataImage', '', None, None),
                                                    ('SlopeDataImage', '', None, None),
                                                    ('BackgroundDataImage', '', None, None),
                                                    ('CalibDiffStart', '', 30, 3),
                                                    ('CalibDiffStep', '', 30, 3),
                                                    ('CalibDiffStop', '', 30, 3),
                                                    ('CalibBreedStart', '', 30, 3),
                                                    ('CalibBreedStep', '', 30, 3),
                                                    ('CalibBreedStop', '', 30, 3),
                                                    ('CalibSpreadStart', '', 30, 3),
                                                    ('CalibSpreadStep', '', 30, 3),
                                                    ('CalibSpreadStop', '', 30, 3),
                                                    ('CalibSlopeStart', '', 30, 3),
                                                    ('CalibSlopeStep', '', 30, 3),
                                                    ('CalibSlopeStop', '', 30, 3),
                                                    ('CalibRoadStart', '', 30, 3),
                                                    ('CalibRoadStep', '', 30, 3),
                                                    ('CalibRoadStop', '', 30, 3),
                                                    ('PredDiffBestFit', '', 30, 3),
                                                    ('PredBreedBestFit', '', 30, 3),
                                                    ('PredSpreadBestFit', '', 30, 3),
                                                    ('PredSlopeBestFit', '', 30, 3),
                                                    ('PredRoadBestFit', '', 30, 3),
                                                    ('RoadGravSensitivity', '', 30, 3),
                                                    ('SlopeSensitivity', '', 30, 3),
                                                    ('CriticalLow', '', 30, 3),
                                                    ('CriticalHigh', '', 30, 3),
                                                    ('CriticalSlope', '', 30, 3),
                                                    ('Boom', '', 30, 3),
                                                    ('Bust', '', 30, 3)]
