'''
Elements container.
Contains information about GUI elements, like variables names, labels, and other elements.
Logic how to setup is in _populate_window method of every window class file.
'''

# Setting radiobuttons
radiobuttons_name_prefix = 'checkBox'
radiobuttons_name_postfix = ['ColorKeyImages',
                             'Animation',
                             'ViewGrowthTypes',
                             'ECHO',
                             'COEFFile',
                             'AVGFile',
                             'STDDEVFile',
                             'MEMORYMap',
                             'LOGGING',
                             'LogLandclassSummary',
                             'LogSlopeWeight',
                             'LogReads',
                             'LogWrites',
                             'LogColortables',
                             'LogTransitionMatrix',
                             'LogUrbanizationAttempts',
                             'LogInitialCoefficients',
                             'LogBaseStatistics',
                             'LogDebug',
                             'LogProcessingStatus',
                             'LogTimings',
                             'WorkingGrids',
                             'RandomSeed'
                             'MontecarloIterations',
                             'AuxDiffusionMult',
                             'AuxDiffustionCoeff',
                             'AuxBreedCoeff',
                             'WriteRatioFile',
                             'WriteSlopeFile',
                             'WriteXYPointsFile',
                             'ViewDeltatronAging']

# Setting buttons
buttons_name_prefix = 'button'
buttons_name_postfix_and_text = [('UrbanDataImage', 'Wybierz z dysku'),
                                 ('RoadDataImage', 'Wybierz z dysku'),
                                 ('LanduseDataImage', 'Wybierz z dysku'),
                                 ('ExcludedDataImage', 'Wybierz z dysku'),
                                 ('SlopeDataImage', 'Wybierz z dysku'),
                                 ('BackgroundDataImage', 'Wybierz z dysku'),
                                 ('OutputFilesColorSettings', 'Output File Color Settings'),
                                 ('ProbabilityColorSettings', 'Probability Colortable Color Settings'),
                                 ('DeltatronAgingColortable', 'Color settings for deltatron aging')]

# Setting labels
labels_name_prefix = 'label'
labels_name_postfix_and_text = [('SleuthModel', 'SLEUTH Model: '),
                                ('Simulation', 'SIMULATION: '),
                                ('ModelDate', 'Model date: '),
                                ('SimulationDate', 'Simulation date: '),
                                ('InputOutputDirectoryMain', 'INput / OUTput DIRECTORY'),
                                ('DataDirectory', 'DATA DIRECTORY: '),
                                ('OutputDirectory', 'OUTPUT DIRECTORY: '),
                                ('PredictionRange', 'PREDICTION RANGE'),
                                ('RunningStatusVariables', 'RUNNING status & variables'),
                                ('StartDate', 'START Date: '),
                                ('StopDate', 'STOP Date: '),
                                ('InputImages', 'INPUT IMAGES'),
                                ('OutputImages', 'OUTPUT IMAGES'),
                                ('Coefficients', 'COEFFICIENTS'),
                                ('SelfModificationParameters', 'SELF-MODIFICATION PARAMETERS'),
                                ('LogFilePreferences', 'LOG FILE preferences'),
                                ('DeltatronAgingSection', 'DELTATRON AGING SECTION'),
                                ('WriteColorKeyImages', 'WRITE COLOR KEY IMAGES'),
                                ('Animation', 'ANIMATION'),
                                ('ViewGrowthTypes', 'VIEW GROWTH TYPES (YES/NO)'),
                                ('GrowthTypePrintWindow', 'GROWTH TYPE PRINT WINDOW'),
                                ('Echo', 'ECHO'),
                                ('COEFFile', 'COEF File'),
                                ('AVGFile', 'AVG File'),
                                ('STDDEVFile', 'STD DEV file'),
                                ('MEMORYmap', 'MEMORY map'),
                                ('LOGGING', 'LOGGING'),
                                ('UrbanImage', 'Urban image: '),
                                ('RoadDataImage', 'Road data image: '),
                                ('LanduseDataImage', 'Land use data image: '),
                                ('ExcludedDataImage', 'Excluded data image: '),
                                ('SlopeDataImage', 'Slope data image: '),
                                ('BackgroundDataImage', 'Background data image: '),
                                ('CalibDiffStart', 'CALIBRATION_DIFFUSION_START'),
                                ('CalibDiffStep', 'CALIBRATION_DIFFUSTION_STEP'),
                                ('CalibDiffStop', 'CALIBRATION_DIFFUSTION_STOP'),
                                ('CalibBreedStart', 'CALIBRATION_BREED_START'),
                                ('CalibBreedStep', 'CALIBRATION_BREED_STEP'),
                                ('CalibBreedStop', 'CALIBRATION_BREED_STOP'),
                                ('CalibSpreadStart', 'CALIBRATION_SPREAD_START'),
                                ('CalibSpreadStep', 'CALIBRATION_SPREAD_STEP'),
                                ('CalibSpreadStop', 'CALIBRATION_SPREAD_STOP'),
                                ('CalibSlopeStart', 'CALIBRATION_SLOPE_START'),
                                ('CalibSlopeStep', 'CALIBRATION_SLOPE_STEP'),
                                ('CalibSlopeStop', 'CALIBRATION_SLOPE_STOP'),
                                ('CalibRoadStart', 'CALIBRATION_ROAD_START'),
                                ('CalibRoadStep', 'CALIBRATION_ROAD_STEP'),
                                ('CalibRoadStop', 'CALIBRATION_ROAD_STOP'),
                                ('PredDiffBestFit', 'PREDICTION_DIFFUSION_BEST_FIT'),
                                ('PredBreedBestFit', 'PREDICTION_BREED_BEST_FIT'),
                                ('PredSpreadBestFit', 'PREDICTION_SPREAD_BEST_FIT'),
                                ('PredSlopeBestFit', 'PREDICTION_SLOPE_BEST_FIT'),
                                ('PredRoadBestFit', 'PREDICTION_ROAD_BEST_FIT'),
                                ('RoadGravSensitivity', 'ROAD_GRAV_SENSITIVITY'),
                                ('SlopeSensitivity', 'SLOPE_SENSITIVITY'),
                                ('CriticalLow', 'CRITICAL_LOW'),
                                ('CriticalHigh', 'CRITICAL_HIGH'),
                                ('CriticalSlope', 'CRITICAL_SLOPE'),
                                ('Boom', 'BOOM'),
                                ('Bust', 'BUST'),
                                ('LogLandclassSummary', 'LOG_LANDCLASS_SUMMARY'),
                                ('LogSlopeWeight', 'LOG_SLOPE_WEIGHT'),
                                ('LogReads', 'LOG_READS'),
                                ('LogWrites', 'LOG_WRITES'),
                                ('LogColortables', 'LOG_COLORTABLES'),
                                ('LogTransitionMatrix', 'LOG_TRANSITION_MATRIX'),
                                ('LogUrbanizationAttempts', 'LOG_URBANIZATION_ATTEMPTS'),
                                ('LogInitialCoefficients', 'LOG_INITIAL_COEFFICIENTS'),
                                ('LogBaseStatistics', 'LOG_BASE_STATISTICS'),
                                ('LogDebug', 'LOG_DEBUG'),
                                ('LogProcessingStatus', 'LOG_PROCESSING_STATUS'),
                                ('LogTimings', 'LOG_TIMINGS'),
                                ('WorkingGrids', 'WORKING GRIDS'),
                                ('RandomSeed', 'RANDOM SEED'),
                                ('MontecarloIterations', 'MONTECARLO ITERATIONS'),
                                ('AuxDiffusionMult', 'AUX_DIFFUSION_MULT'),
                                ('AuxDiffusionCoeff', 'AUX_DIFFUSION_COEFF'),
                                ('AuxBreedCoeff', 'AUX_BREED_COEFF'),
                                ('WriteRatioFile', 'WRITE_RATIO_FILE'),
                                ('WriteSlopeFile', 'WRITE_SLOPE_FILE'),
                                ('WriteXYPointsFile', 'WRITE_XYPOINTS_FILE'),
                                ('ViewDeltatronAging', 'VIEW_DELTATRON_AGING'),
                                ('DeltatronPrintWindow', 'DELTATRON_PRINT_WINDOW')]

labels_qt_align_center = ['labelInputOutputDirectoryMain',
                          'labelPredictionRange',
                          'labelRunningStatusVariables',
                          'labelInputImages',
                          'labelCoefficients',
                          'labelLogFilePreferences',
                          'labelOutputImages',
                          'labelSelfModificationParameters',
                          'labelDeltatronAgingSection']

# Setting lineEdits
line_edits_name_prefix = 'lineEdit'
line_edits_name_postfix_and_text_width_maxlength = [('SleuthModelName', 'Nazwa modelu', None, None),
                                                    ('Simulation', 'Nazwa scenariusza', None, None),
                                                    ('ModelDate', '1.1.1970', 70, 10),
                                                    ('SimulationDate', '1.1.1970', 70, 10),
                                                    ('StartRun', 'Start run', None, None),
                                                    ('EndRun', 'End run', None, None),
                                                    ('StartMc', 'Start mc', None, None),
                                                    ('EndMc', 'End mc', None, None),
                                                    ('StartYear', 'Start year', None, None),
                                                    ('EndYear', 'End year', None, None),
                                                    ('StartRunDeltatron', 'Start run', None, None),
                                                    ('EndRunDeltatron', 'End run', None, None),
                                                    ('StartMcDeltatron', 'Start mc', None, None),
                                                    ('EndMcDeltatron', 'End mc', None, None),
                                                    ('StartYearDeltatron', 'Start year', None, None),
                                                    ('EndYearDeltatron', 'End year', None, None),
                                                    ('UrbanImage', '', None, None),
                                                    ('RoadDataImage', '', None, None),
                                                    ('LanduseDataImage', '', None, None),
                                                    ('ExcludedDataImage', '', None, None),
                                                    ('SlopeDataImage', '', None, None),
                                                    ('BackgroundDataImage', '', None, None),
                                                    ('CalibDiffStart', '', 30, 3),
                                                    ('CalibDiffStep', '', 30, 3),
                                                    ('CalibDiffStop', '', 30, 3),
                                                    ('CalibBreedStart', '', 30, 3),
                                                    ('CalibBreedStep', '', 30, 3),
                                                    ('CalibBreedStop', '', 30, 3),
                                                    ('CalibSpreadStart', '', 30, 3),
                                                    ('CalibSpreadStep', '', 30, 3),
                                                    ('CalibSpreadStop', '', 30, 3),
                                                    ('CalibSlopeStart', '', 30, 3),
                                                    ('CalibSlopeStep', '', 30, 3),
                                                    ('CalibSlopeStop', '', 30, 3),
                                                    ('CalibRoadStart', '', 30, 3),
                                                    ('CalibRoadStep', '', 30, 3),
                                                    ('CalibRoadStop', '', 30, 3),
                                                    ('PredDiffBestFit', '', 30, 3),
                                                    ('PredBreedBestFit', '', 30, 3),
                                                    ('PredSpreadBestFit', '', 30, 3),
                                                    ('PredSlopeBestFit', '', 30, 3),
                                                    ('PredRoadBestFit', '', 30, 3),
                                                    ('RoadGravSensitivity', '', 30, 3),
                                                    ('SlopeSensitivity', '', 30, 3),
                                                    ('CriticalLow', '', 30, 3),
                                                    ('CriticalHigh', '', 30, 3),
                                                    ('CriticalSlope', '', 30, 3),
                                                    ('Boom', '', 30, 3),
                                                    ('Bust', '', 30, 3)]
