CONF_VAR_DICT = {"WRITE_COEFF_FILE": "WRITE_COEFF_FILE(YES/NO)",
                 "WRITE_AVG_FILE": "WRITE_AVG_FILE(YES/NO)",
                 "WRITE_STD_DEV_FILE": "WRITE_STD_DEV_FILE(YES/NO)",
                 "WRITE_MEMORY_MAP": "WRITE_MEMORY_MAP(YES/NO)",
                 "LOGGING": "LOGGING(YES/NO)",
                 "LOG_LANDCLASS_SUMMARY": "LOG_LANDCLASS_SUMMARY(YES/NO)",
                 "LOG_SLOPE_WEIGHTS": "LOG_SLOPE_WEIGHTS(YES/NO)",
                 "LOG_READS": "LOG_READS(YES/NO)",
                 "LOG_WRITES": "LOG_WRITES(YES/NO)",
                 "LOG_COLORTABLES": "LOG_COLORTABLES(YES/NO)",
                 "LOG_PROCESSING_STATUS": "LOG_PROCESSING_STATUS(0:off/1:low verbosity/2:high verbosity)",
                 "LOG_TRANSITION_MATRIX": "LOG_TRANSITION_MATRIX(YES/NO)",
                 "LOG_URBANIZATION_ATTEMPTS": "LOG_URBANIZATION_ATTEMPTS(YES/NO)",
                 "LOG_INITIAL_COEFFICIENTS": "LOG_INITIAL_COEFFICIENTS(YES/NO)",
                 "LOG_BASE_STATISTICS": "LOG_BASE_STATISTICS(YES/NO)",
                 "LOG_DEBUG": "LOG_DEBUG(YES/NO)",
                 "LOG_TIMINGS": "LOG_TIMINGS(0:off/1:low verbosity/2:high verbosity)",
                 "WRITE_COLOR_KEY_IMAGES": "WRITE_COLOR_KEY_IMAGES(YES/NO)",
                 "ECHO_IMAGE_FILES": "ECHO_IMAGE_FILES(YES/NO)",
                 "ANIMATION": "ANIMATION(YES/NO)"}
